name: Pre Merge Checks

on:
  push:
    branches:
      - main

jobs:
  validate_build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0
      - name: Replace Example Content
        env:
          DATA_FETCH_GH_TOKEN: ${{ secrets.DATA_FETCH_GH_TOKEN }}
          DATA_AES_KEY: ${{ secrets.DATA_AES_KEY }}
          DATA_AES_IV: ${{ secrets.DATA_AES_IV }}
        run: |
          ./data/downloadProdSource.sh $DATA_FETCH_GH_TOKEN
          ./data/replaceSecrets.sh -k $DATA_AES_KEY -i $DATA_AES_IV
          chmod a+x ./data/createAsset.sh
          ./data/createAsset.sh
      - name: Create Service Account Key for Flank
        env:
          FLANK_SERVICE_ACCOUNT_KEY: ${{ secrets.FLANK_SERVICE_ACCOUNT_KEY }}
        run: echo $FLANK_SERVICE_ACCOUNT_KEY | base64 -d > app/flank-service-account-key.json
      - name: Run UI Tests
        run: ./gradlew testDebugUnitTest flankRun
