name: Pre Merge Checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0
      - name: Static Analysis
        run: ./gradlew detekt lint
  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0
      - name: Compile Sources
        # Sanity check before proceeding to tests.
        run: ./gradlew compileDebugAndroidTestSources compileDebugSources compileDebugUnitTestSources compileReleaseSources
      - name: Create Service Account Key for Flank
        env:
          FLANK_SERVICE_ACCOUNT_KEY: ${{ secrets.FLANK_SERVICE_ACCOUNT_KEY }}
        run: echo $FLANK_SERVICE_ACCOUNT_KEY | base64 -d > app/flank-service-account-key.json
      - name: Run Tests
        run: ./gradlew testDebugUnitTest flankRun --continue